#define IOCTL_SET_THRESHOLD        21
#define IOCTL_SET_FFT_FREQ         22
#define IOCTL_SET_SIM_DELAY_1      23
#define IOCTL_SET_SIM_DELAY_2      24
#define IOCTL_SET_SIM_DELAY_3      25
#define IOCTL_SET_SIM_PHASE_INC    26
#define IOCTL_SET_SIM_FLAG         27
#define IOCTL_SET_SIM_PING_TIME    28
#define IOCTL_SET_SIM_WAIT_TIME    29
#define IOCTL_SET_PID              30
