# TCL File Generated by Component Editor 17.1
# Sat Jan 13 16:13:12 SBT 2018
# DO NOT MODIFY


# 
# data_controller "data_controller" v1.0
#  2018.01.13.16:13:12
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module data_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME data_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Qsys Component"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME data_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL data_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file data_controller.sv SYSTEM_VERILOG PATH ip/data_controller/data_controller.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point avalon_ss_adc_in
# 
add_interface avalon_ss_adc_in avalon_streaming end
set_interface_property avalon_ss_adc_in associatedClock clock_sink
set_interface_property avalon_ss_adc_in associatedReset reset_sink
set_interface_property avalon_ss_adc_in dataBitsPerSymbol 16
set_interface_property avalon_ss_adc_in errorDescriptor ""
set_interface_property avalon_ss_adc_in firstSymbolInHighOrderBits true
set_interface_property avalon_ss_adc_in maxChannel 0
set_interface_property avalon_ss_adc_in readyLatency 0
set_interface_property avalon_ss_adc_in ENABLED true
set_interface_property avalon_ss_adc_in EXPORT_OF ""
set_interface_property avalon_ss_adc_in PORT_NAME_MAP ""
set_interface_property avalon_ss_adc_in CMSIS_SVD_VARIABLES ""
set_interface_property avalon_ss_adc_in SVD_ADDRESS_GROUP ""

add_interface_port avalon_ss_adc_in adc_data data Input 16
add_interface_port avalon_ss_adc_in adc_channel channel Input 3
add_interface_port avalon_ss_adc_in adc_valid valid Input 1


# 
# connection point avalon_mm_csr0
# 
add_interface avalon_mm_csr0 avalon start
set_interface_property avalon_mm_csr0 addressUnits SYMBOLS
set_interface_property avalon_mm_csr0 associatedClock clock_sink
set_interface_property avalon_mm_csr0 associatedReset reset_sink
set_interface_property avalon_mm_csr0 bitsPerSymbol 8
set_interface_property avalon_mm_csr0 burstOnBurstBoundariesOnly false
set_interface_property avalon_mm_csr0 burstcountUnits WORDS
set_interface_property avalon_mm_csr0 doStreamReads false
set_interface_property avalon_mm_csr0 doStreamWrites false
set_interface_property avalon_mm_csr0 holdTime 0
set_interface_property avalon_mm_csr0 linewrapBursts false
set_interface_property avalon_mm_csr0 maximumPendingReadTransactions 0
set_interface_property avalon_mm_csr0 maximumPendingWriteTransactions 0
set_interface_property avalon_mm_csr0 readLatency 0
set_interface_property avalon_mm_csr0 readWaitTime 1
set_interface_property avalon_mm_csr0 setupTime 0
set_interface_property avalon_mm_csr0 timingUnits Cycles
set_interface_property avalon_mm_csr0 writeWaitTime 0
set_interface_property avalon_mm_csr0 ENABLED true
set_interface_property avalon_mm_csr0 EXPORT_OF ""
set_interface_property avalon_mm_csr0 PORT_NAME_MAP ""
set_interface_property avalon_mm_csr0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_mm_csr0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_mm_csr0 fifo0_csr_address address Output 32
add_interface_port avalon_mm_csr0 fifo0_csr_read read Output 1
add_interface_port avalon_mm_csr0 fifo0_csr_readdata readdata Input 32
add_interface_port avalon_mm_csr0 fifo0_csr_write write Output 1
add_interface_port avalon_mm_csr0 fifo0_csr_writedata writedata Output 32
add_interface_port avalon_mm_csr0 fifo0_csr_waitrequest waitrequest Input 1


# 
# connection point fifo0_in
# 
add_interface fifo0_in avalon_streaming start
set_interface_property fifo0_in associatedClock clock_sink
set_interface_property fifo0_in associatedReset reset_sink
set_interface_property fifo0_in dataBitsPerSymbol 32
set_interface_property fifo0_in errorDescriptor ""
set_interface_property fifo0_in firstSymbolInHighOrderBits true
set_interface_property fifo0_in maxChannel 0
set_interface_property fifo0_in readyLatency 0
set_interface_property fifo0_in ENABLED true
set_interface_property fifo0_in EXPORT_OF ""
set_interface_property fifo0_in PORT_NAME_MAP ""
set_interface_property fifo0_in CMSIS_SVD_VARIABLES ""
set_interface_property fifo0_in SVD_ADDRESS_GROUP ""

add_interface_port fifo0_in fifo0_data data Output 32
add_interface_port fifo0_in fifo0_valid valid Output 1

