# TCL File Generated by Component Editor 17.1
# Sun Jan 07 22:15:34 VLAT 2018
# DO NOT MODIFY


# 
# fft_dft "fft_dft" v1.0
#  2018.01.07.22:15:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fft_dft
# 
set_module_property DESCRIPTION ""
set_module_property NAME fft_dft
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Qsys Component"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fft_dft
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fft_dft
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fft_dft.sv SYSTEM_VERILOG PATH ip/fft_dft/fft_dft.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point fft_in
# 
add_interface fft_in avalon_streaming end
set_interface_property fft_in associatedClock clk
set_interface_property fft_in associatedReset reset
set_interface_property fft_in dataBitsPerSymbol 32
set_interface_property fft_in errorDescriptor ""
set_interface_property fft_in firstSymbolInHighOrderBits true
set_interface_property fft_in maxChannel 0
set_interface_property fft_in readyLatency 0
set_interface_property fft_in ENABLED true
set_interface_property fft_in EXPORT_OF ""
set_interface_property fft_in PORT_NAME_MAP ""
set_interface_property fft_in CMSIS_SVD_VARIABLES ""
set_interface_property fft_in SVD_ADDRESS_GROUP ""

add_interface_port fft_in in_valid valid Input 1
add_interface_port fft_in X data Input 32


# 
# connection point fft_out
# 
add_interface fft_out avalon_streaming start
set_interface_property fft_out associatedClock clk
set_interface_property fft_out associatedReset reset
set_interface_property fft_out dataBitsPerSymbol 64
set_interface_property fft_out errorDescriptor ""
set_interface_property fft_out firstSymbolInHighOrderBits true
set_interface_property fft_out maxChannel 0
set_interface_property fft_out readyLatency 0
set_interface_property fft_out ENABLED true
set_interface_property fft_out EXPORT_OF ""
set_interface_property fft_out PORT_NAME_MAP ""
set_interface_property fft_out CMSIS_SVD_VARIABLES ""
set_interface_property fft_out SVD_ADDRESS_GROUP ""

add_interface_port fft_out Y data Output 64
add_interface_port fft_out out_valid valid Output 1

